FROM openjdk:8

EXPOSE 8080

RUN apt -y update && apt -y upgrade
RUN apt -y install git
RUN git clone https://github.com/docker-hy/spring-example-project
WORKDIR spring-example-project
RUN ./mvnw package
CMD ["java", "-jar", "./target/docker-example-1.1.3.jar"]
